// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_TILETYPE_ASSET_FBS_H_
#define FLATBUFFERS_GENERATED_TILETYPE_ASSET_FBS_H_

#include "flatbuffers/flatbuffers.h"


namespace asset {
namespace fbs {


enum TileType {
  TileType_VOID = 0,
  TileType_WALL = 1,
  TileType_FLOOR = 2,
  TileType_DOOR = 3
};

inline const char **EnumNamesTileType() {
  static const char *names[] = { "VOID", "WALL", "FLOOR", "DOOR", nullptr };
  return names;
}

inline const char *EnumNameTileType(TileType e) { return EnumNamesTileType()[e]; }

}  // namespace fbs
}  // namespace asset

#endif  // FLATBUFFERS_GENERATED_TILETYPE_ASSET_FBS_H_
